### ISSUE TITLE
Mint a DOI for the simulator 

### ISSUE THREAD

**Issue by biavillasboas** [awineteer/odysea-science-simulator#1]
@awineteer, I'm not sure you'd need any additional permissions from JPL/NASA, but if not, I suggest that we [issue a DOI for the simulator through Zenodo](https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content) so we can cite it in the proposal (and other users can reference it too).

**Comment by awineteer** [comment]
Great idea! Just made one here: https://zenodo.org/record/8067125

**Comment by biavillasboas** [comment]
Awesome! Thanks, Alex!
